spring:
  application:
    name: config-service
  profiles:
    active: native  # we are using native because the config server uses a git repo by default
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared  # tells spring where to locate the config files

server:
  port: 8888  # the port where the config-server will be accessible